language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="8998344f-b3e8-4464-89ea-4f0bf1b43488"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - dastan.namazbekov@mail.ru
    on_success: never # default: change
    on_failure: always # default: always